package modelo.entidad;
// Generated 2 may. 2023 17:52:23 by Hibernate Tools 4.3.1



/**
 * DetalleMatricula generated by hbm2java
 */
public class DetalleMatricula  implements java.io.Serializable {


     private int idDetalle;
     private Cursos cursos;
     private Matriculas matriculas;

    public DetalleMatricula() {
    }

	
    public DetalleMatricula(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public DetalleMatricula(int idDetalle, Cursos cursos, Matriculas matriculas) {
       this.idDetalle = idDetalle;
       this.cursos = cursos;
       this.matriculas = matriculas;
    }
   
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Matriculas getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Matriculas matriculas) {
        this.matriculas = matriculas;
    }




}


