package modelo.entidad;
// Generated 2 may. 2023 17:52:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private Integer idEstudiante;
     private String nombre;
     private String apellido;
     private String dni;
     private Date fechaNacimiento;
     private String direccion;
     private String telefono;
     private String email;
     private String contrasena;
     private Set<Pagos> pagoses = new HashSet<Pagos>(0);
     private Set<Matriculas> matriculases = new HashSet<Matriculas>(0);

    public Estudiantes() {
    }

	
    public Estudiantes(String nombre, String apellido, String dni, Date fechaNacimiento, String contrasena) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.fechaNacimiento = fechaNacimiento;
        this.contrasena = contrasena;
    }
    public Estudiantes(String nombre, String apellido, String dni, Date fechaNacimiento, String direccion, String telefono, String email, String contrasena, Set<Pagos> pagoses, Set<Matriculas> matriculases) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.contrasena = contrasena;
       this.pagoses = pagoses;
       this.matriculases = matriculases;
    }
   
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set<Pagos> getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set<Pagos> pagoses) {
        this.pagoses = pagoses;
    }
    public Set<Matriculas> getMatriculases() {
        return this.matriculases;
    }
    
    public void setMatriculases(Set<Matriculas> matriculases) {
        this.matriculases = matriculases;
    }




}


