package modelo.entidad;
// Generated 2 may. 2023 17:52:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matriculas generated by hbm2java
 */
public class Matriculas  implements java.io.Serializable {


     private Integer idMatricula;
     private Estudiantes estudiantes;
     private Secciones secciones;
     private Semestres semestres;
     private String estatus;
     private Date fechaMatricula;
     private Set<Pagos> pagoses = new HashSet<Pagos>(0);
     private Set<DetalleMatricula> detalleMatriculas = new HashSet<DetalleMatricula>(0);

    public Matriculas() {
    }

	
    public Matriculas(Estudiantes estudiantes, Secciones secciones, Semestres semestres, String estatus, Date fechaMatricula) {
        this.estudiantes = estudiantes;
        this.secciones = secciones;
        this.semestres = semestres;
        this.estatus = estatus;
        this.fechaMatricula = fechaMatricula;
    }
    public Matriculas(Estudiantes estudiantes, Secciones secciones, Semestres semestres, String estatus, Date fechaMatricula, Set<Pagos> pagoses, Set<DetalleMatricula> detalleMatriculas) {
       this.estudiantes = estudiantes;
       this.secciones = secciones;
       this.semestres = semestres;
       this.estatus = estatus;
       this.fechaMatricula = fechaMatricula;
       this.pagoses = pagoses;
       this.detalleMatriculas = detalleMatriculas;
    }
   
    public Integer getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(Integer idMatricula) {
        this.idMatricula = idMatricula;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }
    public Semestres getSemestres() {
        return this.semestres;
    }
    
    public void setSemestres(Semestres semestres) {
        this.semestres = semestres;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public Set<Pagos> getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set<Pagos> pagoses) {
        this.pagoses = pagoses;
    }
    public Set<DetalleMatricula> getDetalleMatriculas() {
        return this.detalleMatriculas;
    }
    
    public void setDetalleMatriculas(Set<DetalleMatricula> detalleMatriculas) {
        this.detalleMatriculas = detalleMatriculas;
    }




}


