package modelo.entidad;
// Generated 2 may. 2023 17:52:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Secciones generated by hbm2java
 */
public class Secciones  implements java.io.Serializable {


     private int idSeccion;
     private Cursos cursos;
     private Semestres semestres;
     private String nombre;
     private String aula;
     private Integer capacidad;
     private Set<Matriculas> matriculases = new HashSet<Matriculas>(0);

    public Secciones() {
    }

	
    public Secciones(int idSeccion) {
        this.idSeccion = idSeccion;
    }
    public Secciones(int idSeccion, Cursos cursos, Semestres semestres, String nombre, String aula, Integer capacidad, Set<Matriculas> matriculases) {
       this.idSeccion = idSeccion;
       this.cursos = cursos;
       this.semestres = semestres;
       this.nombre = nombre;
       this.aula = aula;
       this.capacidad = capacidad;
       this.matriculases = matriculases;
    }
   
    public int getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(int idSeccion) {
        this.idSeccion = idSeccion;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Semestres getSemestres() {
        return this.semestres;
    }
    
    public void setSemestres(Semestres semestres) {
        this.semestres = semestres;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAula() {
        return this.aula;
    }
    
    public void setAula(String aula) {
        this.aula = aula;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Set<Matriculas> getMatriculases() {
        return this.matriculases;
    }
    
    public void setMatriculases(Set<Matriculas> matriculases) {
        this.matriculases = matriculases;
    }




}


